
import { compareJobs } from "../src/board-model.js";
const $=id=>document.getElementById(id);
const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node};
const num=value=>Number(value||0).toLocaleString('en-US');
let snapshot=null,busy=false,lastSignature='',clockOffset=0,presenceAllowed=true;
const pageId=crypto.randomUUID();
const now=()=>Date.now()+clockOffset;
function ago(at){const seconds=Math.max(0,Math.floor((now()-at)/1000));return seconds<60?'just now':seconds<3600?Math.floor(seconds/60)+'m ago':seconds<86400?Math.floor(seconds/3600)+'h ago':seconds<604800?Math.floor(seconds/86400)+'d ago':new Date(at).toLocaleDateString('en-US',{month:'short',day:'numeric'})}
function avatar(person){const face=el('span','avatar');face.setAttribute('aria-hidden','true');face.textContent=(person.name||'?').trim().split(/\s+/).slice(0,2).map(n=>Array.from(n)[0]||'').join('').toUpperCase();if(person.picture){try{const u=new URL(person.picture);if(u.protocol==='https:'&&u.hostname.endsWith('.googleusercontent.com')){const img=document.createElement('img');img.src=u.href;img.alt='';img.loading='lazy';img.decoding='async';img.referrerPolicy='no-referrer';img.onerror=()=>img.remove();face.append(img)}}catch{}}return face}
function active(person){return Boolean(person.activeSource&&person.activeUntil>now())}
function updateTimes(){for(const person of snapshot?.members||[]){const item=document.getElementById('member-'+person.id);if(!item)continue;const isActive=active(person);item.querySelector('.dot').hidden=!isActive;const last=item.querySelector('.last-active');last.textContent=isActive&&person.activeSource==='browser'?'On Overflow':person.lastActiveAt?'Last active '+ago(person.lastActiveAt):'';item.title=isActive&&person.activeSource==='browser'?'Viewing Overflow':person.lastActiveAt?'Active in Overflow '+ago(person.lastActiveAt):person.name}for(const node of document.querySelectorAll('.when'))node.textContent=ago(Number(node.dataset.at))}
function renderMembers(members){const list=$('members');const people=[...members].sort((a,b)=>Number(active(b))-Number(active(a))||String(a.name).localeCompare(String(b.name))||String(a.id).localeCompare(String(b.id)));list.replaceChildren(...people.map(person=>{const item=el('li','member');item.id='member-'+person.id;const face=el('span','face');face.append(avatar(person),el('span','dot'));item.append(face,el('div','member-name',person.name),el('div','balance',num(person.balance)),el('div','last-active'));return item}));$('people-empty').hidden=people.length>0;list.setAttribute('aria-busy','false')}
function routePerson(person){const node=el('span','route-person');node.append(avatar(person),el('span','route-name',person.name));node.title=person.name;return node}
const labels={queued:'Waiting for a computer',claimed:'Working',completed:'Done',failed:'Unfinished'};
function showJob(job){const body=$('dialog-body');body.replaceChildren();body.append(el('h2','dialog-title',job.objective||'Untitled task'));const grid=el('dl','detail-grid');const detail=(label,value,wide=false)=>{const wrap=el('div','detail'+(wide?' detail-wide':''));wrap.append(el('dt','',label),el('dd','',value));grid.append(wrap)};detail('Status',labels[job.status]||job.status);detail('Credits',num(job.credits));detail('From',job.requester||'Someone');detail('To',job.worker||'Waiting for a computer');if(job.expectedArtifact)detail('Expected artifact',job.expectedArtifact,true);detail('Created',new Date(job.createdAt).toLocaleString());if(job.completedAt)detail('Finished',new Date(job.completedAt).toLocaleString());if(job.attempts)detail('Attempts',String(job.attempts));if(job.files?.length)detail('Files',job.files.join(', '),true);if(job.artifactChars)detail('Result','Artifact returned · '+num(job.artifactChars)+' characters',true);body.append(grid);$('task-dialog').showModal()}
function renderJobs(jobs,members){const people=new Map(members.map(person=>[person.id,person]));$('jobs').replaceChildren(...[...jobs].sort(compareJobs).map(job=>{const item=el('li','job '+job.status);item.tabIndex=0;item.setAttribute('role','button');item.setAttribute('aria-label','Open task: '+(job.objective||'Untitled task'));item.addEventListener('click',()=>showJob(job));item.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();showJob(job)}});const objective=el('p','objective',job.objective||'Untitled task');objective.title=job.objective||'';const route=el('div','route');route.append(routePerson(people.get(job.requesterMemberId)||{name:job.requester||'Someone'}),el('span','arrow','→'));route.append(job.worker?routePerson(people.get(job.workerMemberId)||{name:job.worker}):el('span','unclaimed','—'));const state=el('div','job-state');const label=el('span','status');const mark=el('span','state-mark',job.status==='completed'?'✓':'');mark.setAttribute('aria-hidden','true');label.append(mark,el('span','',labels[job.status]||job.status));const when=el('time','when');when.dataset.at=job.completedAt||job.claimedAt||job.createdAt;when.dateTime=new Date(Number(when.dataset.at)).toISOString();state.append(label,when);item.append(objective,route,state);return item}));$('jobs-empty').hidden=jobs.length>0;$('jobs').setAttribute('aria-busy','false')}
async function refresh(){if(busy)return;busy=true;try{const r=await fetch('/api/activity',{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();clockOffset=Number(data.now||Date.now())-Date.now();snapshot=data;const members=data.members||[],jobs=data.jobs||[];const signature=JSON.stringify([members,jobs]);if(signature!==lastSignature){renderMembers(members);renderJobs(jobs,members);lastSignature=signature}updateTimes();$('error').hidden=true}catch{$('error').textContent=snapshot?'Couldn’t refresh. Showing the last update.':'Couldn’t load Overflow.';$('error').hidden=false;$('members').setAttribute('aria-busy','false');$('jobs').setAttribute('aria-busy','false');updateTimes()}finally{busy=false}}
async function heartbeat(visible=!document.hidden){if(!presenceAllowed)return;try{const r=await fetch('/api/presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pageId,visible}),keepalive:true});if(r.status===401)presenceAllowed=false}catch{}}
refresh();if(!document.hidden)heartbeat();
setInterval(()=>{if(!document.hidden)refresh()},10000);
setInterval(()=>{if(!document.hidden)heartbeat()},30000);
setInterval(updateTimes,5000);
document.addEventListener('visibilitychange',()=>{heartbeat(!document.hidden);if(!document.hidden){presenceAllowed=true;refresh()}});
window.addEventListener('pagehide',()=>heartbeat(false));
window.addEventListener('pageshow',event=>{if(event.persisted){presenceAllowed=true;refresh();heartbeat()}});
$('dialog-close').addEventListener('click',()=>$('task-dialog').close());
$('task-dialog').addEventListener('click',event=>{if(event.target===$('task-dialog'))$('task-dialog').close()});
