import { build } from 'vite';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const client = await build({
  root, configFile: false,
  build: {
    write: false, minify: false,
    lib: { entry: 'ui/board-client.js', name: 'OverflowBoard', formats: ['iife'] },
  },
});
await build({
  root, configFile: false,
  build: {
    ssr: 'ui/render.jsx', outDir: '.ui-build', emptyOutDir: true,
    rollupOptions: { output: { entryFileNames: 'render.mjs' } },
  },
});
const { renderPages } = await import(new URL('../.ui-build/render.mjs', import.meta.url));
const outputs = (Array.isArray(client) ? client : [client]).flatMap(result => result.output);
const script = outputs.find(file => file.type === 'chunk' && file.isEntry).code;
const pages = renderPages(script);
await mkdir(new URL('../src/generated/', import.meta.url), { recursive: true });
await writeFile(new URL('../src/generated/site-pages.js', import.meta.url),
  '// Generated by npm run build:ui. Edit ui/ instead.\nexport const SITE_PAGES = ' + JSON.stringify(pages) + ';\n');
console.log('Built dashboard, privacy, and terms with one shared site layout.');
